vim.keymap.set('t', '<C-g>', '<C-W>:tabp<CR>')
vim.keymap.set('t', '<C-j>', '<C-W>j')
vim.keymap.set('t', '<C-k>', '<C-W>k')
vim.keymap.set('t', '<C-h>', '<C-W>h')
vim.keymap.set('t', '<C-l>', '<C-W>l')
