describe('nvim-config bootstrap settings', function()
  it('moves plugin globals into Lazy init blocks', function()
    local nvim_tree = require('plugins.nvim-tree')
    local markdown_preview = require('plugins.markdown-preview')
    local img_paste = require('plugins.img-paste')

    nvim_tree.init()
    markdown_preview.init()
    img_paste.init()

    assert.are.equal(1, vim.g.loaded_netrw)
    assert.are.equal(1, vim.g.loaded_netrwPlugin)
    assert.are.same({ 'markdown' }, vim.g.mkdp_filetypes)
    assert.are.equal(0, vim.g.mkdp_auto_close)
    assert.are.equal(1, vim.g.mkdp_refresh_slow)
    assert.are.equal('img', vim.g.mdip_imgname)
  end)
end)
