local function require_core_modules()
  vim.g.mapleader = ' '

  require('config.autocmds')
  require('config.commands')
  require('config.constants')
  require('config.comments')
  require('config.functions')
  require('config.keymaps')
  require('config.options')
end

describe('nvim-config core Lua modules', function()
  it('load in init order without errors', function()
    assert.has_no.errors(require_core_modules)
  end)

  it('registers baseline Lua commands and keymaps', function()
    require_core_modules()

    local commands = vim.api.nvim_get_commands({})
    assert.is_truthy(commands.CloseAll)
    assert.is_truthy(commands.FoldOpen)
    assert.is_truthy(commands.FindLocal)
    assert.is_truthy(commands.Bufdo)
    assert.is_truthy(commands.Cnext)
    assert.is_truthy(commands.Cprev)
    assert.is_truthy(commands.Figlet)
    assert.is_truthy(commands.Grep)
    assert.is_truthy(commands.Lnext)
    assert.is_truthy(commands.Lprev)
    assert.is_truthy(commands.Mani)
    assert.is_truthy(commands.ReplaceMwithBlank)
    assert.is_truthy(commands.ReplaceMwithNewLine)
    assert.is_truthy(commands.SpellToggle)
    assert.is_truthy(commands.StartAsyncNeoVim)
    assert.is_truthy(commands.TodoPrompt)
    assert.is_truthy(commands.Windo)
    assert.is_truthy(commands.Windofast)
    assert.is_truthy(commands.EchoSelection)
    assert.is_truthy(commands.FilterAndSaveOldfiles)
    assert.is_nil(commands.ViraEnable)

    local todo_map = vim.fn.maparg('<Space>ti', 'n', false, true)
    local history_map = vim.fn.maparg('<Space>nh', 'n', false, true)
    local copilot_commit_map = vim.fn.maparg('<Space>ag', 'n', false, true)
    local copilot_toggle_normal_map = vim.fn.maparg('<Space>ac', 'n', false, true)
    local copilot_fix_diagnostic_map = vim.fn.maparg('<Space>af', 'n', false, true)
    local copilot_quick_chat_normal_map = vim.fn.maparg('<Space>aq', 'n', false, true)
    local copilot_tests_map = vim.fn.maparg('<Space>at', 'n', false, true)
    local copilot_toggle_visual_map = vim.fn.maparg('<Space>ac', 'v', false, true)
    local copilot_docs_visual_map = vim.fn.maparg('<Space>ad', 'v', false, true)
    local copilot_explain_visual_map = vim.fn.maparg('<Space>ae', 'v', false, true)
    local copilot_fix_visual_map = vim.fn.maparg('<Space>af', 'v', false, true)
    local copilot_optimize_visual_map = vim.fn.maparg('<Space>ao', 'v', false, true)
    local copilot_quick_chat_visual_map = vim.fn.maparg('<Space>aq', 'v', false, true)
    local copilot_review_visual_map = vim.fn.maparg('<Space>ar', 'v', false, true)
    local append_colon_map = vim.fn.maparg('<Space>a:', 'n', false, true)
    local append_comma_map = vim.fn.maparg('<Space>a,', 'n', false, true)
    local append_period_map = vim.fn.maparg('<Space>a.', 'n', false, true)
    local append_semicolon_map = vim.fn.maparg('<Space>a;', 'n', false, true)
    local copy_file_path_map = vim.fn.maparg('<Space>cfp', 'n', false, true)
    local copy_working_dir_map = vim.fn.maparg('<Space>cwd', 'n', false, true)
    local close_toggle_map = vim.fn.maparg('<Space>ct', 'n', false, true)
    local close_all_map = vim.fn.maparg('<Space>ca', 'n', false, true)
    local rerun_command_map = vim.fn.maparg('qr', 'n', false, true)
    local command_history_map = vim.fn.maparg('q;', 'n', false, true)
    local comment_paragraph_map = vim.fn.maparg('cp', 'n', false, true)
    local git_diff_terminal_map = vim.fn.maparg('<Space>rd', 'n', false, true)
    local git_fugitive_diff_map = vim.fn.maparg('<Space>gd', 'n', false, true)
    local git_difftool_map = vim.fn.maparg('<Space>gdt', 'n', false, true)
    local git_status_map = vim.fn.maparg('<Space>gs', 'n', false, true)
    local open_explorer_map = vim.fn.maparg('<Space>oe', 'n', false, true)
    local open_browser_map = vim.fn.maparg('<Space>ob', 'n', false, true)
    local tables_report_map = vim.fn.maparg('<Space>tp', 'n', false, true)
    local weather_report_map = vim.fn.maparg('<Space>cw', 'n', false, true)
    local quickfix_map = vim.fn.maparg('<Space>q', 'n', false, true)
    local quickfix_next_map = vim.fn.maparg('<C-f>', 'n', false, true)
    local quickfix_prev_map = vim.fn.maparg('<C-d>', 'n', false, true)
    local comment_prompt_map = vim.fn.maparg('cii', 'n', false, true)
    local comment_marker_map = vim.fn.maparg('ci1', 'n', false, true)
    local comment_yank_map = vim.fn.maparg('cy', 'n', false, true)
    local quit_insert_map = vim.fn.maparg('<C-q>', 'i', false, true)
    local quit_normal_map = vim.fn.maparg('<C-q>', 'n', false, true)
    local quit_window_map = vim.fn.maparg('<C-w>', 'n', false, true)
    local quick_quit_map = vim.fn.maparg('qq', 'n', false, true)
    local normal_paste_map = vim.fn.maparg('<C-v>', 'n', false, true)
    local insert_paste_map = vim.fn.maparg('<C-v>', 'i', false, true)
    local command_paste_map = vim.fn.maparg('<C-v>', 'c', false, true)
    local spell_toggle_map = vim.fn.maparg('<Space>st', 'n', false, true)
    local mani_status_map = vim.fn.maparg('<Space>ms', 'n', false, true)
    local mani_up_map = vim.fn.maparg('<Space>mu', 'n', false, true)
    local grep_code_map = vim.fn.maparg('<Space>fc', 'n', false, true)
    local grep_notes_map = vim.fn.maparg('<Space>fn', 'n', false, true)
    local grep_repo_map = vim.fn.maparg('<Space>fg', 'n', false, true)
    local grep_repo_word_map = vim.fn.maparg('<Space>gw', 'n', false, true)
    local grep_file_map = vim.fn.maparg('<Space>fl', 'n', false, true)
    local grep_file_word_map = vim.fn.maparg('<Space>fw', 'n', false, true)
    local search_multiple_terms_map = vim.fn.maparg('<Space>/', 'n', false, true)
    local sort_paragraph_map = vim.fn.maparg('<Space>so', 'n', false, true)
    local suspend_map = vim.fn.maparg('<C-z>', 'n', false, true)
    local redo_normal_map = vim.fn.maparg('<C-y>', 'n', false, true)
    local redo_insert_map = vim.fn.maparg('<C-y>', 'i', false, true)
    local fileformat_dos_map = vim.fn.maparg('<Space>ctd', 'n', false, true)
    local fileformat_mac_map = vim.fn.maparg('<Space>ctm', 'n', false, true)
    local fileformat_unix_map = vim.fn.maparg('<Space>ctu', 'n', false, true)
    local line_start_map = vim.fn.maparg('H', 'n', false, true)
    local line_end_map = vim.fn.maparg('L', 'n', false, true)
    local line_start_visual_map = vim.fn.maparg('H', 'v', false, true)
    local line_end_operator_map = vim.fn.maparg('L', 'o', false, true)
    local exact_mark_map = vim.fn.maparg("'", 'n', false, true)
    local wrapped_down_map = vim.fn.maparg('j', 'n', false, true)
    local wrapped_up_map = vim.fn.maparg('k', 'n', false, true)
    local alternate_buffer_map = vim.fn.maparg('<BS>', 'n', false, true)
    local blank_below_map = vim.fn.maparg('<Space>aj', 'n', false, true)
    local blank_above_map = vim.fn.maparg('<Space>ak', 'n', false, true)
    local blank_around_map = vim.fn.maparg('<Space>al', 'n', false, true)
    local force_quit_map = vim.fn.maparg('Q', 'n', false, true)
    local quick_write_map = vim.fn.maparg('qw', 'n', false, true)
    local control_save_normal_map = vim.fn.maparg('<C-s>', 'n', false, true)
    local control_save_insert_map = vim.fn.maparg('<C-s>', 'i', false, true)
    local scroll_up_map = vim.fn.maparg('K', 'n', false, true)
    local scroll_down_map = vim.fn.maparg('J', 'n', false, true)
    local window_down_map = vim.fn.maparg('qj', 'n', false, true)
    local window_up_map = vim.fn.maparg('qk', 'n', false, true)
    local window_left_map = vim.fn.maparg('qh', 'n', false, true)
    local window_right_map = vim.fn.maparg('ql', 'n', false, true)
    local control_left_window_map = vim.fn.maparg('<C-h>', 'n', false, true)
    local control_right_window_map = vim.fn.maparg('<C-l>', 'n', false, true)
    local goto_last_insert_tab_map = vim.fn.maparg('gI', 'n', false, true)
    local goto_global_declaration_tab_map = vim.fn.maparg('gT', 'n', false, true)
    local goto_local_declaration_tab_map = vim.fn.maparg('gt', 'n', false, true)
    local goto_local_declaration_split_map = vim.fn.maparg('gs', 'n', false, true)
    local goto_local_declaration_vsplit_map = vim.fn.maparg('gv', 'n', false, true)
    local current_file_tab_map = vim.fn.maparg('<C-t>', 'n', false, true)
    local next_tab_map = vim.fn.maparg('<C-Tab>', 'n', false, true)
    local previous_tab_map = vim.fn.maparg('<Tab>', 'n', false, true)
    local goto_file_map = vim.fn.maparg('gf', 'n', false, true)
    local yank_to_eol_map = vim.fn.maparg('Y', 'n', false, true)
    local yank_all_map = vim.fn.maparg('<Space>ya', 'n', false, true)
    local rename_word_map = vim.fn.maparg('<Space>rw', 'n', false, true)
    local rename_visual_map = vim.fn.maparg('<Space>rw', 'v', false, true)

    assert.are.equal('<Space>ti', todo_map.lhs)
    assert.are.equal('<Space>nh', history_map.lhs)
    assert.are.equal('<Space>ag', copilot_commit_map.lhs)
    assert.are.equal('<Space>ac', copilot_toggle_normal_map.lhs)
    assert.are.equal('<Space>af', copilot_fix_diagnostic_map.lhs)
    assert.are.equal('<Space>aq', copilot_quick_chat_normal_map.lhs)
    assert.are.equal('<Space>at', copilot_tests_map.lhs)
    assert.are.equal('<Space>ac', copilot_toggle_visual_map.lhs)
    assert.are.equal('<Space>ad', copilot_docs_visual_map.lhs)
    assert.are.equal('<Space>ae', copilot_explain_visual_map.lhs)
    assert.are.equal('<Space>af', copilot_fix_visual_map.lhs)
    assert.are.equal('<Space>ao', copilot_optimize_visual_map.lhs)
    assert.are.equal('<Space>aq', copilot_quick_chat_visual_map.lhs)
    assert.are.equal('<Space>ar', copilot_review_visual_map.lhs)
    assert.are.equal('<Space>a:', append_colon_map.lhs)
    assert.are.equal('<Space>a,', append_comma_map.lhs)
    assert.are.equal('<Space>a.', append_period_map.lhs)
    assert.are.equal('<Space>a;', append_semicolon_map.lhs)
    assert.are.equal('<Space>cfp', copy_file_path_map.lhs)
    assert.are.equal('<Space>cwd', copy_working_dir_map.lhs)
    assert.are.equal('<Space>ct', close_toggle_map.lhs)
    assert.are.equal('<Space>ca', close_all_map.lhs)
    assert.are.equal('qr', rerun_command_map.lhs)
    assert.are.equal('q;', command_history_map.lhs)
    assert.are.equal('cp', comment_paragraph_map.lhs)
    assert.are.equal('<Space>rd', git_diff_terminal_map.lhs)
    assert.are.equal('<Space>gd', git_fugitive_diff_map.lhs)
    assert.are.equal('<Space>gdt', git_difftool_map.lhs)
    assert.are.equal('<Space>gs', git_status_map.lhs)
    assert.are.equal('<Space>oe', open_explorer_map.lhs)
    assert.are.equal('<Space>ob', open_browser_map.lhs)
    assert.are.equal('<Space>tp', tables_report_map.lhs)
    assert.are.equal('<Space>cw', weather_report_map.lhs)
    assert.are.equal('<Space>q', quickfix_map.lhs)
    assert.are.equal('<C-F>', quickfix_next_map.lhs)
    assert.are.equal('<C-D>', quickfix_prev_map.lhs)
    assert.are.equal('cii', comment_prompt_map.lhs)
    assert.are.equal('ci1', comment_marker_map.lhs)
    assert.are.equal('cy', comment_yank_map.lhs)
    assert.is_truthy(quit_insert_map.lhs ~= nil and quit_insert_map.lhs ~= '')
    assert.is_truthy(quit_normal_map.lhs ~= nil and quit_normal_map.lhs ~= '')
    assert.is_truthy(quit_window_map.lhs ~= nil and quit_window_map.lhs ~= '')
    assert.is_truthy(quick_quit_map.lhs ~= nil and quick_quit_map.lhs ~= '')
    assert.is_truthy(normal_paste_map.lhs ~= nil and normal_paste_map.lhs ~= '')
    assert.is_truthy(insert_paste_map.lhs ~= nil and insert_paste_map.lhs ~= '')
    assert.is_truthy(command_paste_map.lhs ~= nil and command_paste_map.lhs ~= '')
    assert.are.equal('<Space>st', spell_toggle_map.lhs)
    assert.are.equal('<Space>ms', mani_status_map.lhs)
    assert.are.equal('<Space>mu', mani_up_map.lhs)
    assert.are.equal('<Space>fc', grep_code_map.lhs)
    assert.are.equal('<Space>fn', grep_notes_map.lhs)
    assert.are.equal('<Space>fg', grep_repo_map.lhs)
    assert.are.equal('<Space>gw', grep_repo_word_map.lhs)
    assert.are.equal('<Space>fl', grep_file_map.lhs)
    assert.are.equal('<Space>fw', grep_file_word_map.lhs)
    assert.are.equal('<Space>/', search_multiple_terms_map.lhs)
    assert.are.equal('<Space>so', sort_paragraph_map.lhs)
    assert.are.equal('<C-Z>', suspend_map.lhs)
    assert.are.equal('<C-Y>', redo_normal_map.lhs)
    assert.are.equal('<C-Y>', redo_insert_map.lhs)
    assert.are.equal('<Space>ctd', fileformat_dos_map.lhs)
    assert.are.equal('<Space>ctm', fileformat_mac_map.lhs)
    assert.are.equal('<Space>ctu', fileformat_unix_map.lhs)
    assert.are.equal([[/\v<C-r>/\|]], search_multiple_terms_map.rhs)
    assert.are.equal('vip:sort<CR>', sort_paragraph_map.rhs)
    assert.are.equal('<Nop>', suspend_map.rhs)
    assert.are.equal('<C-r>', redo_normal_map.rhs)
    assert.are.equal('<Esc><C-r>', redo_insert_map.rhs)
    assert.are.equal('^', line_start_map.rhs)
    assert.are.equal('$', line_end_map.rhs)
    assert.are.equal('^', line_start_visual_map.rhs)
    assert.are.equal('$', line_end_operator_map.rhs)
    assert.are.equal('`', exact_mark_map.rhs)
    assert.are.equal(1, wrapped_down_map.expr)
    assert.are.equal(1, wrapped_up_map.expr)
    assert.are.equal('<C-^>', alternate_buffer_map.rhs)
    assert.are.equal('<Space>aj', blank_below_map.lhs)
    assert.are.equal('<Space>ak', blank_above_map.lhs)
    assert.are.equal('<Space>al', blank_around_map.lhs)
    assert.are.equal(':q!<CR>', force_quit_map.rhs)
    assert.are.equal(':w<CR>', quick_write_map.rhs)
    assert.are.equal(':w<CR>', control_save_normal_map.rhs)
    assert.are.equal('<Esc>:w<CR>', control_save_insert_map.rhs)
    assert.are.equal('5k', scroll_up_map.rhs)
    assert.are.equal('5j', scroll_down_map.rhs)
    assert.are.equal('<C-W>j', window_down_map.rhs)
    assert.are.equal('<C-W>k', window_up_map.rhs)
    assert.are.equal('<C-W>h', window_left_map.rhs)
    assert.are.equal('<C-W>l', window_right_map.rhs)
    assert.are.equal('<C-W>h', control_left_window_map.rhs)
    assert.are.equal('<C-W>l', control_right_window_map.rhs)
    assert.are.equal('gI', goto_last_insert_tab_map.lhs)
    assert.are.equal('gT', goto_global_declaration_tab_map.lhs)
    assert.are.equal('gt', goto_local_declaration_tab_map.lhs)
    assert.are.equal('gs', goto_local_declaration_split_map.lhs)
    assert.are.equal('gv', goto_local_declaration_vsplit_map.lhs)
    assert.are.equal('<C-T>', current_file_tab_map.lhs)
    assert.are.equal('<C-Tab>', next_tab_map.lhs)
    assert.are.equal('<Tab>', previous_tab_map.lhs)
    assert.are.equal('gf', goto_file_map.lhs)
    assert.are.equal('mm:tabe %<CR>`m`^zMzvzz', goto_last_insert_tab_map.rhs)
    assert.are.equal('mm:tabe %<CR>`mgDzMzvzz', goto_global_declaration_tab_map.rhs)
    assert.are.equal('mm:tabe %<CR>`mgdzMzvzz', goto_local_declaration_tab_map.rhs)
    assert.are.equal('mm:sp %<CR>`mgdzMzvzz', goto_local_declaration_split_map.rhs)
    assert.are.equal('mm:vs %<CR>`mgdzMzvzz', goto_local_declaration_vsplit_map.rhs)
    assert.are.equal('mm:tabe <C-r>%<CR>`m', current_file_tab_map.rhs)
    assert.are.equal(':tabnext<CR>', next_tab_map.rhs)
    assert.are.equal(':tabprevious<CR>', previous_tab_map.rhs)
    assert.are.equal('gf', goto_file_map.rhs)
    assert.are.equal('y$', yank_to_eol_map.rhs)
    assert.are.equal('<Space>ya', yank_all_map.lhs)
    assert.are.equal('<Space>rw', rename_word_map.lhs)
    assert.are.equal('<Space>rw', rename_visual_map.lhs)
    assert.are.equal('@:', rerun_command_map.rhs)
    assert.are.equal('q:', command_history_map.rhs)
    assert.are.equal('', vim.fn.maparg('<Space>sv', 'n'))
    assert.are.equal(1, vim.fn.exists('*EditCommonFile'))
    assert.are.equal(1, vim.fn.exists('*Quit'))
    assert.are.equal(1, vim.fn.exists('*BufDo'))
    assert.are.equal(1, vim.fn.exists('*GetBufferList'))
    assert.are.equal(1, vim.fn.exists('*GetCommentString'))
    assert.are.equal(1, vim.fn.exists('*GetTODOs'))
    assert.are.equal(1, vim.fn.exists('*Figlet'))
    assert.are.equal(1, vim.fn.exists('*FontSizePlus'))
    assert.are.equal(1, vim.fn.exists('*FontSizeMinus'))
    assert.are.equal(1, vim.fn.exists('*WinDo'))
    assert.are.equal(1, vim.fn.exists('*PasteClipboard'))
    assert.is_true(vim.o.foldtext:find('config.folds', 1, true) ~= nil)
    assert.is_true(vim.o.tabline:find('config.tabline', 1, true) ~= nil)

    require('config.keymaps').set_terminal_keymaps(0)
    local terminal_tab_map = vim.fn.maparg('<C-g>', 't', false, true)
    local terminal_down_map = vim.fn.maparg('<C-j>', 't', false, true)
    local terminal_up_map = vim.fn.maparg('<C-k>', 't', false, true)
    local terminal_left_map = vim.fn.maparg('<C-h>', 't', false, true)
    local terminal_right_map = vim.fn.maparg('<C-l>', 't', false, true)
    assert.are.equal('<C-G>', terminal_tab_map.lhs)
    assert.are.equal(1, terminal_tab_map.buffer)
    assert.are.equal('<C-W>:tabp<CR>', terminal_tab_map.rhs)
    assert.are.equal('<C-W>j', terminal_down_map.rhs)
    assert.are.equal('<C-W>k', terminal_up_map.rhs)
    assert.are.equal('<C-W>h', terminal_left_map.rhs)
    assert.are.equal('<C-W>l', terminal_right_map.rhs)
  end)

  it('registers migrated toggle commands with the same state changes', function()
    require_core_modules()

    vim.g.term_close = ''
    vim.cmd('silent CloseToggle')
    assert.are.equal('++close', vim.g.term_close)
    vim.cmd('silent CloseToggle')
    assert.are.equal('', vim.g.term_close)

    vim.opt_local.spell = false
    vim.cmd('silent SpellToggle')
    assert.is_true(vim.wo.spell)
    vim.cmd('silent SpellToggle')
    assert.is_false(vim.wo.spell)
  end)
end)
