local function require_core_modules()
  vim.g.mapleader = ' '

  require('config.autocmds')
  require('config.commands')
  require('config.constants')
  require('config.comments')
  require('config.functions')
  require('config.keymaps')
  require('config.options')
end

describe('nvim-config core Lua modules', function()
  it('load in init order without errors', function()
    assert.has_no.errors(require_core_modules)
  end)

  it('registers baseline Lua commands and keymaps', function()
    require_core_modules()

    local commands = vim.api.nvim_get_commands({})
    assert.is_truthy(commands.CloseAll)
    assert.is_truthy(commands.FoldOpen)
    assert.is_truthy(commands.FindLocal)
    assert.is_truthy(commands.Bufdo)
    assert.is_truthy(commands.Cnext)
    assert.is_truthy(commands.Cprev)
    assert.is_truthy(commands.Lnext)
    assert.is_truthy(commands.Lprev)
    assert.is_truthy(commands.SpellToggle)
    assert.is_truthy(commands.TodoPrompt)
    assert.is_truthy(commands.Windo)
    assert.is_truthy(commands.Windofast)
    assert.is_truthy(commands.EchoSelection)
    assert.is_truthy(commands.FilterAndSaveOldfiles)
    assert.is_nil(commands.ViraEnable)

    local todo_map = vim.fn.maparg('<Space>ti', 'n', false, true)
    local history_map = vim.fn.maparg('<Space>nh', 'n', false, true)
    local quickfix_map = vim.fn.maparg('<Space>q', 'n', false, true)
    local quickfix_next_map = vim.fn.maparg('<C-f>', 'n', false, true)
    local quickfix_prev_map = vim.fn.maparg('<C-d>', 'n', false, true)
    local comment_prompt_map = vim.fn.maparg('cii', 'n', false, true)
    local comment_marker_map = vim.fn.maparg('ci1', 'n', false, true)
    local comment_yank_map = vim.fn.maparg('cy', 'n', false, true)
    local quit_insert_map = vim.fn.maparg('<C-q>', 'i', false, true)
    local quit_normal_map = vim.fn.maparg('<C-q>', 'n', false, true)
    local quit_window_map = vim.fn.maparg('<C-w>', 'n', false, true)
    local quick_quit_map = vim.fn.maparg('qq', 'n', false, true)
    local normal_paste_map = vim.fn.maparg('<C-v>', 'n', false, true)
    local insert_paste_map = vim.fn.maparg('<C-v>', 'i', false, true)
    local command_paste_map = vim.fn.maparg('<C-v>', 'c', false, true)
    local spell_toggle_map = vim.fn.maparg('<Space>st', 'n', false, true)

    assert.are.equal('<Space>ti', todo_map.lhs)
    assert.are.equal('<Space>nh', history_map.lhs)
    assert.are.equal('<Space>q', quickfix_map.lhs)
    assert.are.equal('<C-F>', quickfix_next_map.lhs)
    assert.are.equal('<C-D>', quickfix_prev_map.lhs)
    assert.are.equal('cii', comment_prompt_map.lhs)
    assert.are.equal('ci1', comment_marker_map.lhs)
    assert.are.equal('cy', comment_yank_map.lhs)
    assert.is_truthy(quit_insert_map.lhs ~= nil and quit_insert_map.lhs ~= '')
    assert.is_truthy(quit_normal_map.lhs ~= nil and quit_normal_map.lhs ~= '')
    assert.is_truthy(quit_window_map.lhs ~= nil and quit_window_map.lhs ~= '')
    assert.is_truthy(quick_quit_map.lhs ~= nil and quick_quit_map.lhs ~= '')
    assert.is_truthy(normal_paste_map.lhs ~= nil and normal_paste_map.lhs ~= '')
    assert.is_truthy(insert_paste_map.lhs ~= nil and insert_paste_map.lhs ~= '')
    assert.is_truthy(command_paste_map.lhs ~= nil and command_paste_map.lhs ~= '')
    assert.are.equal('<Space>st', spell_toggle_map.lhs)
    assert.are.equal(1, vim.fn.exists('*Quit'))
    assert.are.equal(1, vim.fn.exists('*BufDo'))
    assert.are.equal(1, vim.fn.exists('*WinDo'))
    assert.are.equal(1, vim.fn.exists('*PasteClipboard'))
    assert.is_true(vim.o.foldtext:find('config.folds', 1, true) ~= nil)
    assert.is_true(vim.o.tabline:find('config.tabline', 1, true) ~= nil)
  end)

  it('registers migrated toggle commands with the same state changes', function()
    require_core_modules()

    vim.g.term_close = ''
    vim.cmd('silent CloseToggle')
    assert.are.equal('++close', vim.g.term_close)
    vim.cmd('silent CloseToggle')
    assert.are.equal('', vim.g.term_close)

    vim.opt_local.spell = false
    vim.cmd('silent SpellToggle')
    assert.is_true(vim.wo.spell)
    vim.cmd('silent SpellToggle')
    assert.is_false(vim.wo.spell)
  end)
end)
