local function require_core_modules()
  vim.g.mapleader = ' '

  require('config.autocmds')
  require('config.commands')
  require('config.constants')
  require('config.comments')
  require('config.functions')
  require('config.keymaps')
  require('config.options')
end

describe('nvim-config core Lua modules', function()
  it('load in init order without errors', function()
    assert.has_no.errors(require_core_modules)
  end)

  it('registers baseline Lua commands and keymaps', function()
    require_core_modules()

    local commands = vim.api.nvim_get_commands({})
    assert.is_truthy(commands.CloseAll)
    assert.is_truthy(commands.FoldOpen)
    assert.is_truthy(commands.FindLocal)
    assert.is_truthy(commands.Bufdo)
    assert.is_truthy(commands.Cnext)
    assert.is_truthy(commands.Cprev)
    assert.is_truthy(commands.Figlet)
    assert.is_truthy(commands.Grep)
    assert.is_truthy(commands.Lnext)
    assert.is_truthy(commands.Lprev)
    assert.is_truthy(commands.Mani)
    assert.is_truthy(commands.ReplaceMwithBlank)
    assert.is_truthy(commands.ReplaceMwithNewLine)
    assert.is_truthy(commands.SpellToggle)
    assert.is_truthy(commands.StartAsyncNeoVim)
    assert.is_truthy(commands.TodoPrompt)
    assert.is_truthy(commands.Windo)
    assert.is_truthy(commands.Windofast)
    assert.is_truthy(commands.EchoSelection)
    assert.is_truthy(commands.FilterAndSaveOldfiles)
    assert.is_nil(commands.ViraEnable)

    local todo_map = vim.fn.maparg('<Space>ti', 'n', false, true)
    local history_map = vim.fn.maparg('<Space>nh', 'n', false, true)
    local quickfix_map = vim.fn.maparg('<Space>q', 'n', false, true)
    local quickfix_next_map = vim.fn.maparg('<C-f>', 'n', false, true)
    local quickfix_prev_map = vim.fn.maparg('<C-d>', 'n', false, true)
    local comment_prompt_map = vim.fn.maparg('cii', 'n', false, true)
    local comment_marker_map = vim.fn.maparg('ci1', 'n', false, true)
    local comment_yank_map = vim.fn.maparg('cy', 'n', false, true)
    local quit_insert_map = vim.fn.maparg('<C-q>', 'i', false, true)
    local quit_normal_map = vim.fn.maparg('<C-q>', 'n', false, true)
    local quit_window_map = vim.fn.maparg('<C-w>', 'n', false, true)
    local quick_quit_map = vim.fn.maparg('qq', 'n', false, true)
    local normal_paste_map = vim.fn.maparg('<C-v>', 'n', false, true)
    local insert_paste_map = vim.fn.maparg('<C-v>', 'i', false, true)
    local command_paste_map = vim.fn.maparg('<C-v>', 'c', false, true)
    local spell_toggle_map = vim.fn.maparg('<Space>st', 'n', false, true)
    local mani_status_map = vim.fn.maparg('<Space>ms', 'n', false, true)
    local mani_up_map = vim.fn.maparg('<Space>mu', 'n', false, true)
    local grep_code_map = vim.fn.maparg('<Space>fc', 'n', false, true)
    local grep_notes_map = vim.fn.maparg('<Space>fn', 'n', false, true)
    local grep_repo_map = vim.fn.maparg('<Space>fg', 'n', false, true)
    local grep_repo_word_map = vim.fn.maparg('<Space>gw', 'n', false, true)
    local grep_file_map = vim.fn.maparg('<Space>fl', 'n', false, true)
    local grep_file_word_map = vim.fn.maparg('<Space>fw', 'n', false, true)
    local fileformat_dos_map = vim.fn.maparg('<Space>ctd', 'n', false, true)
    local fileformat_mac_map = vim.fn.maparg('<Space>ctm', 'n', false, true)
    local fileformat_unix_map = vim.fn.maparg('<Space>ctu', 'n', false, true)
    local line_start_map = vim.fn.maparg('H', 'n', false, true)
    local line_end_map = vim.fn.maparg('L', 'n', false, true)
    local line_start_visual_map = vim.fn.maparg('H', 'v', false, true)
    local line_end_operator_map = vim.fn.maparg('L', 'o', false, true)
    local exact_mark_map = vim.fn.maparg("'", 'n', false, true)
    local wrapped_down_map = vim.fn.maparg('j', 'n', false, true)
    local wrapped_up_map = vim.fn.maparg('k', 'n', false, true)
    local alternate_buffer_map = vim.fn.maparg('<BS>', 'n', false, true)
    local blank_below_map = vim.fn.maparg('<Space>aj', 'n', false, true)
    local blank_above_map = vim.fn.maparg('<Space>ak', 'n', false, true)
    local blank_around_map = vim.fn.maparg('<Space>al', 'n', false, true)
    local force_quit_map = vim.fn.maparg('Q', 'n', false, true)
    local quick_write_map = vim.fn.maparg('qw', 'n', false, true)
    local control_save_normal_map = vim.fn.maparg('<C-s>', 'n', false, true)
    local control_save_insert_map = vim.fn.maparg('<C-s>', 'i', false, true)
    local scroll_up_map = vim.fn.maparg('K', 'n', false, true)
    local scroll_down_map = vim.fn.maparg('J', 'n', false, true)
    local window_down_map = vim.fn.maparg('qj', 'n', false, true)
    local window_up_map = vim.fn.maparg('qk', 'n', false, true)
    local window_left_map = vim.fn.maparg('qh', 'n', false, true)
    local window_right_map = vim.fn.maparg('ql', 'n', false, true)
    local control_left_window_map = vim.fn.maparg('<C-h>', 'n', false, true)
    local control_right_window_map = vim.fn.maparg('<C-l>', 'n', false, true)
    local yank_to_eol_map = vim.fn.maparg('Y', 'n', false, true)
    local yank_all_map = vim.fn.maparg('<Space>ya', 'n', false, true)

    assert.are.equal('<Space>ti', todo_map.lhs)
    assert.are.equal('<Space>nh', history_map.lhs)
    assert.are.equal('<Space>q', quickfix_map.lhs)
    assert.are.equal('<C-F>', quickfix_next_map.lhs)
    assert.are.equal('<C-D>', quickfix_prev_map.lhs)
    assert.are.equal('cii', comment_prompt_map.lhs)
    assert.are.equal('ci1', comment_marker_map.lhs)
    assert.are.equal('cy', comment_yank_map.lhs)
    assert.is_truthy(quit_insert_map.lhs ~= nil and quit_insert_map.lhs ~= '')
    assert.is_truthy(quit_normal_map.lhs ~= nil and quit_normal_map.lhs ~= '')
    assert.is_truthy(quit_window_map.lhs ~= nil and quit_window_map.lhs ~= '')
    assert.is_truthy(quick_quit_map.lhs ~= nil and quick_quit_map.lhs ~= '')
    assert.is_truthy(normal_paste_map.lhs ~= nil and normal_paste_map.lhs ~= '')
    assert.is_truthy(insert_paste_map.lhs ~= nil and insert_paste_map.lhs ~= '')
    assert.is_truthy(command_paste_map.lhs ~= nil and command_paste_map.lhs ~= '')
    assert.are.equal('<Space>st', spell_toggle_map.lhs)
    assert.are.equal('<Space>ms', mani_status_map.lhs)
    assert.are.equal('<Space>mu', mani_up_map.lhs)
    assert.are.equal('<Space>fc', grep_code_map.lhs)
    assert.are.equal('<Space>fn', grep_notes_map.lhs)
    assert.are.equal('<Space>fg', grep_repo_map.lhs)
    assert.are.equal('<Space>gw', grep_repo_word_map.lhs)
    assert.are.equal('<Space>fl', grep_file_map.lhs)
    assert.are.equal('<Space>fw', grep_file_word_map.lhs)
    assert.are.equal('<Space>ctd', fileformat_dos_map.lhs)
    assert.are.equal('<Space>ctm', fileformat_mac_map.lhs)
    assert.are.equal('<Space>ctu', fileformat_unix_map.lhs)
    assert.are.equal('^', line_start_map.rhs)
    assert.are.equal('$', line_end_map.rhs)
    assert.are.equal('^', line_start_visual_map.rhs)
    assert.are.equal('$', line_end_operator_map.rhs)
    assert.are.equal('`', exact_mark_map.rhs)
    assert.are.equal(1, wrapped_down_map.expr)
    assert.are.equal(1, wrapped_up_map.expr)
    assert.are.equal('<C-^>', alternate_buffer_map.rhs)
    assert.are.equal('<Space>aj', blank_below_map.lhs)
    assert.are.equal('<Space>ak', blank_above_map.lhs)
    assert.are.equal('<Space>al', blank_around_map.lhs)
    assert.are.equal(':q!<CR>', force_quit_map.rhs)
    assert.are.equal(':w<CR>', quick_write_map.rhs)
    assert.are.equal(':w<CR>', control_save_normal_map.rhs)
    assert.are.equal('<Esc>:w<CR>', control_save_insert_map.rhs)
    assert.are.equal('5k', scroll_up_map.rhs)
    assert.are.equal('5j', scroll_down_map.rhs)
    assert.are.equal('<C-W>j', window_down_map.rhs)
    assert.are.equal('<C-W>k', window_up_map.rhs)
    assert.are.equal('<C-W>h', window_left_map.rhs)
    assert.are.equal('<C-W>l', window_right_map.rhs)
    assert.are.equal('<C-W>h', control_left_window_map.rhs)
    assert.are.equal('<C-W>l', control_right_window_map.rhs)
    assert.are.equal('y$', yank_to_eol_map.rhs)
    assert.are.equal('<Space>ya', yank_all_map.lhs)
    assert.are.equal(1, vim.fn.exists('*EditCommonFile'))
    assert.are.equal(1, vim.fn.exists('*Quit'))
    assert.are.equal(1, vim.fn.exists('*BufDo'))
    assert.are.equal(1, vim.fn.exists('*GetBufferList'))
    assert.are.equal(1, vim.fn.exists('*GetCommentString'))
    assert.are.equal(1, vim.fn.exists('*GetTODOs'))
    assert.are.equal(1, vim.fn.exists('*Figlet'))
    assert.are.equal(1, vim.fn.exists('*WinDo'))
    assert.are.equal(1, vim.fn.exists('*PasteClipboard'))
    assert.is_true(vim.o.foldtext:find('config.folds', 1, true) ~= nil)
    assert.is_true(vim.o.tabline:find('config.tabline', 1, true) ~= nil)

    require('config.keymaps').set_terminal_keymaps()
    local terminal_tab_map = vim.fn.maparg('<C-g>', 't', false, true)
    local terminal_down_map = vim.fn.maparg('<C-j>', 't', false, true)
    local terminal_up_map = vim.fn.maparg('<C-k>', 't', false, true)
    local terminal_left_map = vim.fn.maparg('<C-h>', 't', false, true)
    local terminal_right_map = vim.fn.maparg('<C-l>', 't', false, true)
    assert.are.equal('<C-G>', terminal_tab_map.lhs)
    assert.are.equal('<C-W>:tabp<CR>', terminal_tab_map.rhs)
    assert.are.equal('<C-W>j', terminal_down_map.rhs)
    assert.are.equal('<C-W>k', terminal_up_map.rhs)
    assert.are.equal('<C-W>h', terminal_left_map.rhs)
    assert.are.equal('<C-W>l', terminal_right_map.rhs)
  end)

  it('registers migrated toggle commands with the same state changes', function()
    require_core_modules()

    vim.g.term_close = ''
    vim.cmd('silent CloseToggle')
    assert.are.equal('++close', vim.g.term_close)
    vim.cmd('silent CloseToggle')
    assert.are.equal('', vim.g.term_close)

    vim.opt_local.spell = false
    vim.cmd('silent SpellToggle')
    assert.is_true(vim.wo.spell)
    vim.cmd('silent SpellToggle')
    assert.is_false(vim.wo.spell)
  end)
end)
