local function load_options()
  package.loaded['config.constants'] = nil
  package.loaded['config.options'] = nil

  require('config.constants')
  require('config.options')
end

describe('nvim-config option preservation', function()
  it('keeps the remaining legacy globals and editor defaults in Lua', function()
    load_options()

    assert.are.equal('$HOME/git', vim.env.CODE)
    assert.are.equal('hidden', vim.g.display_hidden)
    assert.are.equal('{{{', vim.g.fold_marker_string)
    assert.are.equal('', vim.g.term_close)

    assert.is_true(vim.o.number)
    assert.are.equal(8, vim.o.scrolloff)
    assert.is_true(vim.o.wildmenu)
    assert.is_true(vim.o.showcmd)
    assert.is_false(vim.o.showmode)
    assert.is_true(vim.o.lazyredraw)
    assert.is_true(vim.o.linebreak)
    assert.are.equal(2, vim.o.laststatus)

    assert.is_true(vim.o.shada:find("'2000", 1, true) ~= nil)
    assert.is_true(vim.o.shada:find('rterm://', 1, true) ~= nil)
    assert.are.equal(500, vim.o.timeoutlen)
    assert.are.equal(0, vim.o.ttimeoutlen)
    assert.is_true(vim.o.backspace:find('indent', 1, true) ~= nil)
    assert.is_true(vim.o.backspace:find('eol', 1, true) ~= nil)
    assert.is_true(vim.o.backspace:find('start', 1, true) ~= nil)
    assert.are.equal(500, vim.o.updatetime)
    assert.are.equal('all', vim.o.virtualedit)

    assert.is_true(vim.o.wildignore:find('package.json', 1, true) ~= nil)
    assert.is_true(vim.o.wildignore:find('package%-lock.json') ~= nil)
    assert.is_true(vim.o.wildignore:find('node_modules', 1, true) ~= nil)
    assert.is_false(vim.o.swapfile)
    assert.are.equal('unnamedplus', vim.o.clipboard)
    assert.are.equal('xsel clipboard', vim.g.clipboard.name)
    assert.are.same({ 'clipsy', 'copy' }, vim.g.clipboard.copy['+'])
    assert.are.same({ 'clipsy', 'paste' }, vim.g.clipboard.paste['+'])

    assert.is_true(vim.o.splitright)
    assert.is_true(vim.o.autochdir)
    assert.are.equal('', vim.o.mouse)
    assert.is_true(vim.o.modeline)
    assert.are.equal(5, vim.o.modelines)
    assert.is_true(vim.o.autoread)
    assert.are.equal(vim.fn.expand('~/git/Notes/Main/en.utf-8.add'), vim.o.spellfile)
    assert.is_true(vim.o.nrformats:find('octal', 1, true) == nil)

    assert.is_true(vim.o.autoindent)
    assert.are.equal(4, vim.o.tabstop)
    assert.are.equal(4, vim.o.softtabstop)
    assert.are.equal(0, vim.o.shiftwidth)
    assert.is_true(vim.o.expandtab)
    assert.is_true(vim.o.smarttab)

    assert.is_true(vim.o.incsearch)
    assert.is_true(vim.o.hlsearch)
    assert.is_true(vim.o.ignorecase)
    assert.is_true(vim.o.smartcase)
  end)
end)
